language: android
sudo: required
#os: [linux]
dist: trusty

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - EMULATOR_API=29
    - EMULATOR_ABI=x86
    - EMULATOR_TAG=default # can be google_apis
    - PATH=$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API
    - extra-android-support
    - sys-img-armeabi-v7a-$ANDROID_API


before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

script:
  - echo $ANDROID_HOME # We assume this is correctly set when setting path
  - sdkmanager --list || true # Look at the packages
  - avdmanager
  - android list targets
#  - ./gradlew assembleAndroidTest
  - export EMULATOR="system-images;android-$EMULATOR_API;$EMULATOR_TAG;$EMULATOR_ABI"
  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f # Create emulator virtual device
  - emulator -avd test -no-window -no-accel -no-snapshot -camera-back emulated -camera-front emulated -memory 2048 -writable-system & # Launch
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
#  - ./gradlew assembleDebug

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-1.0-debug.apk
  skip_cleanup: true
  name: dev-build-$USER-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs