#Run this while adding .yml 
#git update-index --chmod=+x gradlew
language: android
sudo: required
dist: trusty
# dist: trusty or jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23


before_install:
  - yes | sdkmanager "platforms;android-23"

script:
    - ./gradlew assembleDebug
