language: android
sudo: required
#os: [linux]
dist: trusty

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - EMULATOR_API=29
    - EMULATOR_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API
    - extra-android-support
    - sys-img-armeabi-v7a-$ANDROID_API


before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"

script:
  - android list targets
  - ./gradlew assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_API --abi $EMULATOR_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
#  - ./gradlew assembleDebug

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-1.0-debug.apk
  skip_cleanup: true
  name: dev-build-$USER-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs